# Interlock/HAProxy
interlock:
  image: ehazlett/interlock:latest
  ports:
    - "80:80"
  volumes:
    - /var/lib/docker:/etc/docker
  environment:
    - <PLUGIN_NAME>_PROXY_BACKEND_OVERRIDE_ADDRESS=<IP/DNS of Engine>
  command: "--swarm-url tcp://<IP_OR_DNS_OF_SWARM_MASTER_OR_ENGINE>:<PORT> --debug --plugin <PLUGIN_NAME=nginx or haproxy> start"
# DB
db:
  image: mongo
  expose:
    - 27017
  command: --smallfiles
# Web
web:
  build: .
  environment:
     - INTERLOCK_DATA={"hostname":"docker-training.com","domain":"docker-training.com"}
  ports:
    - "5000"
  links:
   - db:db

